/** \brief This header file declares functions for Output File Processing.
*
* The output file generated by the simulator is processed
* to produce a more readable format. The data is stored in 
* output file *_proc.txt in a table format as shown below:
*
*Time           value  port                component
*00:00:10:000   20     out                 generator_con  
*00:00:20:000   1      packet_sent_out     sender1        
*00:00:20:000   11     data_out            sender1        
*00:00:23:000   11     out                 subnet1        
*00:00:33:000   1      out                 receiver1      
*00:00:36:000   1      out                 subnet2  
*
* Peter Bliznyuk-Kvitko
* Carleton University
*
*/

#ifndef _FILE_PROCESS_HPP_
#define _FILE_PROCESS_HPP_

/** 
* Function that gets the data from the input file
* and writes the data in new format to the output file
* @param fin input file name string
* @param fout output file name string
*/
void output_file_process(char *fin, char *fout);

/** 
* Function that reads the input file into a string
* in blocks of data.
* @param fin input file name string
* @return string with file content
*/
char *read_file(char *fin);

/** 
* Function that outputs the data contained
* in the file string to the output file
* following specified format
* @param fout output file name string
* @param file string with file content
*/
void write_file(char *fout, char *file);


#endif // _FILE_PROCESS_HPP_